name: deploy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v3
      - run: pip install virtualenv
      - run: make
      - run: make push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
