name: deploy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v2
    - run: pip install virtualenv
    - run: make
    - name: self test newly built action
      uses: ./
    - run: make push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
