name: tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11
          - macos-10.15
          - windows-2022
          - windows-2019
    runs-on: ${{ matrix.os }}
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4.1.0
      - run: pip install virtualenv
      - run: make
      - name: self test newly built action
        uses: ./
